name: Pytest & flake8 control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pytest and flake8
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8
 
      - name: Run tests
        run: |
          pytest ~/github_actions/.github/workflows/file_test.py
          pytest -vv

      - name: Run flake8
        run: |
          flake8

